name: sudo_jwt
description: JWT for Dart
version: 2.0.0
homepage: https://sudo.dog

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
